sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    
    #安装 imagemagick
    - sudo apt-get install imagemagick
    
    #安装解压包
    - sudo apt install p7zip-full
    
    
script:
  - bash test.sh
  
  - cd 实验4/
  #解压
  - 7z x web_log.tsv.7z
  - ls
  
  #work1
  - bash imgsPro.sh
  - bash imgsPro.sh -h
  - bash imgsPro.sh -q 50 testimg
  - bash imgsPro.sh -c 60 testimg
  - bash imgsPro.sh -w "aaaaaaaa" testimg
  - bash imgsPro.sh -r "pre" "bbbbbbb" testimg
  - bash imgsPro.sh -t testimg
  #work2
  - bash playerAssess.sh 
  - bash playerAssess.sh -h
  - bash playerAssess.sh -a
  - bash playerAssess.sh -p
  - bash playerAssess.sh -n
  - bash playerAssess.sh -o
  #work3
  - bash webServerAccess.sh
  - bash webServerAccess.sh -h
  - bash webServerAccess.sh -o
  - bash webServerAccess.sh -i
  - bash webServerAccess.sh -u
  - bash webServerAccess.sh -r
  - bash webServerAccess.sh -s
  - bash webServerAccess.sh -a
  

after_script:
  - /usr/bin/shellcheck test.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
